package nl.vanparerensoftwaredevelopment.saltthepassmanager.common.theme

import androidx.compose.ui.graphics.Color

/*
 * Colors used for the themes. These were automatically generated using
 * the theme builder at https://m3.material.io/theme-builder
 */

val md_theme_light_primary = Color(0xFF6650A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE8DDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF22005D)
val md_theme_light_secondary = Color(0xFF6650A4)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF22005D)
val md_theme_light_tertiary = Color(0xFF006973)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF92F1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFF)
val md_theme_light_onBackground = Color(0xFF001E2E)
val md_theme_light_surface = Color(0xFFFBFCFF)
val md_theme_light_onSurface = Color(0xFF001E2E)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFE5F2FF)
val md_theme_light_inverseSurface = Color(0xFF00344C)
val md_theme_light_inversePrimary = Color(0xFFCFBDFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6650A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFCFBDFF)
val md_theme_dark_onPrimary = Color(0xFF371E73)
val md_theme_dark_primaryContainer = Color(0xFF4E378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFE8DDFF)
val md_theme_dark_secondary = Color(0xFFCFBDFF)
val md_theme_dark_onSecondary = Color(0xFF371E73)
val md_theme_dark_secondaryContainer = Color(0xFF4E378A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DDFF)
val md_theme_dark_tertiary = Color(0xFF4ED8EA)
val md_theme_dark_onTertiary = Color(0xFF00363C)
val md_theme_dark_tertiaryContainer = Color(0xFF004F57)
val md_theme_dark_onTertiaryContainer = Color(0xFF92F1FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001E2E)
val md_theme_dark_onBackground = Color(0xFFC7E7FF)
val md_theme_dark_surface = Color(0xFF001E2E)
val md_theme_dark_onSurface = Color(0xFFC7E7FF)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF001E2E)
val md_theme_dark_inverseSurface = Color(0xFFC7E7FF)
val md_theme_dark_inversePrimary = Color(0xFF6650A4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFCFBDFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF9A83DB)