name: Release Builds
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false
    
    - name: Execute Gradle build
      run: ./gradlew desktop:packageDistributionForCurrentOS
      
    - name: Upload builds
      uses: actions/upload-artifact@v3
      with:
        name: desktop-${{ matrix.os }}
        path: |
          desktop/build/compose/binaries/main/dmg/*
          desktop/build/compose/binaries/main/deb/*
          desktop/build/compose/binaries/main/msi/*

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Unpack Keystore File
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEYSTORE_FILE }}

    - name: Unpack keystore credentials
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'local.properties'
        encodedString: ${{ secrets.LOCAL_PROPERTIES }}

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false
    
    - name: Execute Gradle build
      run: ./gradlew android:build

    - name: List all generated APK files
      uses: the-coding-turtle/ga-file-list@v0.2
      with:
        directory: "android/build"
        file_extension: "apk"
      
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: android/build/outputs/apk/release/android-release.apk
